name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8

      - name: Build and Publish Package
        run: |
          ./gradlew clean build
          echo "//registry.npmjs.org/:_authToken=\${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          echo "email=\${{ secrets.EMAIL }}" >> ~/.npmrc
          echo "username=\${{ secrets.USERNAME }}" >> ~/.npmrc
          
          ./gradlew publish -PrepoUsername=\${{ secrets.REPO_USERNAME }} -PrepoPassword=\${{ secrets.REPO_PASSWORD }} -PpackageVersion=07082019